"""empty message

Revision ID: 001b5ef7ba2d
Revises: 9962320d52b4
Create Date: 2019-12-19 18:58:01.222866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001b5ef7ba2d'
down_revision = '9962320d52b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('month')
    # ### end Alembic commands ###
