"""empty message

Revision ID: 045288ac2fd3
Revises: 3e4d89c19941
Create Date: 2020-09-28 10:47:33.784990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045288ac2fd3'
down_revision = '3e4d89c19941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_dataset_data', sa.Column('r_data', sa.Float(), nullable=True))
    op.add_column('chart_dataset_data', sa.Column('x_data', sa.Float(), nullable=True))
    op.add_column('chart_dataset_data', sa.Column('y_data', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_dataset_data', 'y_data')
    op.drop_column('chart_dataset_data', 'x_data')
    op.drop_column('chart_dataset_data', 'r_data')
    # ### end Alembic commands ###
