"""empty message

Revision ID: 0577bf89a0f3
Revises: be664441bce4
Create Date: 2020-07-16 12:13:50.429100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0577bf89a0f3'
down_revision = 'be664441bce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('essay', sa.Column('type_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'essay', 'essay_type', ['type_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'essay', type_='foreignkey')
    op.drop_column('essay', 'type_fk')
    op.drop_table('essay_type')
    # ### end Alembic commands ###
