"""empty message

Revision ID: 1444bf909ab0
Revises: 2367c00904b2
Create Date: 2020-03-16 20:01:31.956919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1444bf909ab0'
down_revision = '2367c00904b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('category_label', sa.String(), nullable=True),
    sa.Column('timeline_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timeline_fk'], ['timeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_category')
    # ### end Alembic commands ###
