"""empty message

Revision ID: 1c756d0ea25c
Revises: 96c9642e901d
Create Date: 2020-03-16 21:23:02.180939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c756d0ea25c'
down_revision = '96c9642e901d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_category_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('timeline_category_fk', sa.Integer(), nullable=True),
    sa.Column('event_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_fk'], ['event.id'], ),
    sa.ForeignKeyConstraint(['timeline_category_fk'], ['timeline_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_category_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('timeline_category_fk', sa.Integer(), nullable=True),
    sa.Column('person_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_fk'], ['person.id'], ),
    sa.ForeignKeyConstraint(['timeline_category_fk'], ['timeline_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_category_person')
    op.drop_table('timeline_category_event')
    # ### end Alembic commands ###
