"""empty message

Revision ID: 1ec048babdab
Revises: f6664b39e735
Create Date: 2020-01-04 11:11:23.868979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec048babdab'
down_revision = 'f6664b39e735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_author', sa.Column('reference_fk', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_author', 'reference_fk')
    # ### end Alembic commands ###
