"""empty message

Revision ID: 2367c00904b2
Revises: 31c1630c7a2c
Create Date: 2020-03-15 07:07:56.962848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2367c00904b2'
down_revision = '31c1630c7a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('person_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_fk'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'description')
    op.drop_table('person_note')
    # ### end Alembic commands ###
