"""empty message

Revision ID: 2a710b51b5f2
Revises: c623d1335f8e
Create Date: 2019-12-24 11:41:02.701868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a710b51b5f2'
down_revision = 'c623d1335f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('event_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_fk'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('period_start_day', sa.Integer(), nullable=True),
    sa.Column('period_start_month_fk', sa.Integer(), nullable=True),
    sa.Column('period_start_year', sa.Integer(), nullable=True),
    sa.Column('period_start_era_fk', sa.Integer(), nullable=True),
    sa.Column('period_end_day', sa.Integer(), nullable=True),
    sa.Column('period_end_month_fk', sa.Integer(), nullable=True),
    sa.Column('period_end_year', sa.Integer(), nullable=True),
    sa.Column('period_end_era_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_end_era_fk'], ['era.id'], ),
    sa.ForeignKeyConstraint(['period_end_month_fk'], ['month.id'], ),
    sa.ForeignKeyConstraint(['period_start_era_fk'], ['era.id'], ),
    sa.ForeignKeyConstraint(['period_start_month_fk'], ['month.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_period')
    op.drop_table('event_note')
    op.drop_table('event')
    # ### end Alembic commands ###
