"""empty message

Revision ID: 2cc04335eb0e
Revises: 36dbe4d18af7
Create Date: 2020-02-06 11:19:16.283493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc04335eb0e'
down_revision = '36dbe4d18af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_start_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_start_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
