"""empty message

Revision ID: 3959362c23f4
Revises: 2cc04335eb0e
Create Date: 2020-02-06 11:19:39.093364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3959362c23f4'
down_revision = '2cc04335eb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_start_year', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_start_year')
    # ### end Alembic commands ###
