"""empty message

Revision ID: 3e4d89c19941
Revises: 6d03547f2e9c
Create Date: 2020-09-28 10:47:10.054337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e4d89c19941'
down_revision = '6d03547f2e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_dataset_data', 'z_data')
    op.drop_column('chart_dataset_data', 'r_data')
    op.drop_column('chart_dataset_data', 'y_data')
    op.drop_column('chart_dataset_data', 'x_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_dataset_data', sa.Column('x_data', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chart_dataset_data', sa.Column('y_data', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chart_dataset_data', sa.Column('r_data', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chart_dataset_data', sa.Column('z_data', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
