"""empty message

Revision ID: 407b35b5a0cc
Revises: 2a710b51b5f2
Create Date: 2019-12-24 12:01:06.181310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407b35b5a0cc'
down_revision = '2a710b51b5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_period', sa.Column('event_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_period', 'event', ['event_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_period', type_='foreignkey')
    op.drop_column('event_period', 'event_fk')
    # ### end Alembic commands ###
