"""empty message

Revision ID: 61bd619f8182
Revises: afe164411b28
Create Date: 2020-01-29 19:02:11.070534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61bd619f8182'
down_revision = 'afe164411b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_reference')
    op.add_column('person', sa.Column('reference_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'reference', ['reference_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'reference_fk')
    op.create_table('person_reference',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reference_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reference_fk'], ['reference.id'], name='person_reference_reference_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_reference_pkey')
    )
    # ### end Alembic commands ###
