"""empty message

Revision ID: 6346ae9de08b
Revises: 9b9e7c18a1c8
Create Date: 2020-02-12 18:43:15.564429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6346ae9de08b'
down_revision = '9b9e7c18a1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('sub_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference', 'sub_title')
    # ### end Alembic commands ###
