"""empty message

Revision ID: 6515e5b10cad
Revises: 1ec048babdab
Create Date: 2020-01-04 11:19:17.883573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6515e5b10cad'
down_revision = '1ec048babdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reference_author', 'reference', ['reference_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_author', type_='foreignkey')
    # ### end Alembic commands ###
