"""empty message

Revision ID: 69e0bfdd0ed7
Revises: 0577bf89a0f3
Create Date: 2020-07-16 13:15:20.869164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e0bfdd0ed7'
down_revision = '0577bf89a0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_biography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('essay_fk', sa.Integer(), nullable=True),
    sa.Column('person_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['essay_fk'], ['essay.id'], ),
    sa.ForeignKeyConstraint(['person_fk'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_biography')
    # ### end Alembic commands ###
