"""empty message

Revision ID: 69e25d8c8be1
Revises: d47ac9f9883b
Create Date: 2020-02-06 12:00:22.077309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e25d8c8be1'
down_revision = 'd47ac9f9883b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_end_year', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_end_year')
    # ### end Alembic commands ###
