"""empty message

Revision ID: 76359437b051
Revises: dee4af14784f
Create Date: 2019-12-28 16:40:58.057777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76359437b051'
down_revision = 'dee4af14784f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_published',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month_fk', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('era_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['era_fk'], ['era.id'], ),
    sa.ForeignKeyConstraint(['month_fk'], ['month.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_published')
    op.drop_table('reference_author')
    op.drop_table('reference')
    # ### end Alembic commands ###
