"""empty message

Revision ID: 8cf10c9efd0e
Revises: 7bee80c80442
Create Date: 2020-01-04 18:44:27.644419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf10c9efd0e'
down_revision = '7bee80c80442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('published_day', sa.Integer(), nullable=True))
    op.add_column('reference', sa.Column('published_era_fk', sa.Integer(), nullable=True))
    op.add_column('reference', sa.Column('published_month_fk', sa.Integer(), nullable=True))
    op.add_column('reference', sa.Column('published_year', sa.Integer(), nullable=True))
    op.drop_constraint('reference_month_fk_fkey', 'reference', type_='foreignkey')
    op.drop_constraint('reference_era_fk_fkey', 'reference', type_='foreignkey')
    op.create_foreign_key(None, 'reference', 'era', ['published_era_fk'], ['id'])
    op.create_foreign_key(None, 'reference', 'month', ['published_month_fk'], ['id'])
    op.drop_column('reference', 'month_fk')
    op.drop_column('reference', 'year')
    op.drop_column('reference', 'day')
    op.drop_column('reference', 'era_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('era_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reference', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reference', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reference', sa.Column('month_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.create_foreign_key('reference_era_fk_fkey', 'reference', 'era', ['era_fk'], ['id'])
    op.create_foreign_key('reference_month_fk_fkey', 'reference', 'month', ['month_fk'], ['id'])
    op.drop_column('reference', 'published_year')
    op.drop_column('reference', 'published_month_fk')
    op.drop_column('reference', 'published_era_fk')
    op.drop_column('reference', 'published_day')
    # ### end Alembic commands ###
