"""empty message

Revision ID: 9b9e7c18a1c8
Revises: ac67d7941c9d
Create Date: 2020-02-06 14:35:34.612336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9e7c18a1c8'
down_revision = 'ac67d7941c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('timeline_fk', sa.Integer(), nullable=True),
    sa.Column('event_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_fk'], ['event.id'], ),
    sa.ForeignKeyConstraint(['timeline_fk'], ['timeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('timeline_fk', sa.Integer(), nullable=True),
    sa.Column('person_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_fk'], ['person.id'], ),
    sa.ForeignKeyConstraint(['timeline_fk'], ['timeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_person')
    op.drop_table('timeline_event')
    # ### end Alembic commands ###
