"""empty message

Revision ID: 9d1b12c9d3b0
Revises: a63f08f91a20
Create Date: 2020-03-12 17:34:55.491212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d1b12c9d3b0'
down_revision = 'a63f08f91a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('culture_period')
    op.drop_table('culture')
    op.drop_table('culture_reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture_reference',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reference_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reference_fk'], ['reference.id'], name='culture_reference_reference_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='culture_reference_pkey')
    )
    op.create_table('culture',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('culture_id_seq'::regclass)"), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='culture_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('culture_period',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('period_start_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_start_month_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_start_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_start_era_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_end_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_end_month_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_end_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_end_era_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('culture_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['culture_fk'], ['culture.id'], name='culture_period_culture_fk_fkey'),
    sa.ForeignKeyConstraint(['period_end_era_fk'], ['era.id'], name='culture_period_period_end_era_fk_fkey'),
    sa.ForeignKeyConstraint(['period_end_month_fk'], ['month.id'], name='culture_period_period_end_month_fk_fkey'),
    sa.ForeignKeyConstraint(['period_start_era_fk'], ['era.id'], name='culture_period_period_start_era_fk_fkey'),
    sa.ForeignKeyConstraint(['period_start_month_fk'], ['month.id'], name='culture_period_period_start_month_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='culture_period_pkey')
    )
    # ### end Alembic commands ###
