"""empty message

Revision ID: a63f08f91a20
Revises: 6346ae9de08b
Create Date: 2020-02-27 07:18:04.570383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63f08f91a20'
down_revision = '6346ae9de08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_event', sa.Column('is_shadow', sa.Boolean(), nullable=True))
    op.add_column('timeline_event', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_event', 'priority')
    op.drop_column('timeline_event', 'is_shadow')
    # ### end Alembic commands ###
