"""empty message

Revision ID: b89fdcefeaed
Revises: 21bd0b167c10
Create Date: 2020-06-17 13:46:06.693033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89fdcefeaed'
down_revision = '21bd0b167c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('chart_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_fk'], ['chart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('chart_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_fk'], ['chart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_dataset_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('x_data', sa.Integer(), nullable=True),
    sa.Column('y_data', sa.Integer(), nullable=True),
    sa.Column('r_data', sa.Integer(), nullable=True),
    sa.Column('chart_dataset_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_dataset_fk'], ['chart_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_dataset_data')
    op.drop_table('chart_label')
    op.drop_table('chart_dataset')
    op.drop_table('chart')
    # ### end Alembic commands ###
