"""empty message

Revision ID: bfb5d8811922
Revises: 9d1b12c9d3b0
Create Date: 2020-03-13 18:28:44.636715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb5d8811922'
down_revision = '9d1b12c9d3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('event_fk', sa.Integer(), nullable=True),
    sa.Column('tag_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_fk'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_fk'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('person_fk', sa.Integer(), nullable=True),
    sa.Column('tag_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_fk'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tag_fk'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_tag')
    op.drop_table('event_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
