"""empty message

Revision ID: c623d1335f8e
Revises: 001b5ef7ba2d
Create Date: 2019-12-21 13:58:18.417953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c623d1335f8e'
down_revision = '001b5ef7ba2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('period_start_day', sa.Integer(), nullable=True),
    sa.Column('period_start_month_fk', sa.Integer(), nullable=True),
    sa.Column('period_start_year', sa.Integer(), nullable=True),
    sa.Column('period_start_era_fk', sa.Integer(), nullable=True),
    sa.Column('period_end_day', sa.Integer(), nullable=True),
    sa.Column('period_end_month_fk', sa.Integer(), nullable=True),
    sa.Column('period_end_year', sa.Integer(), nullable=True),
    sa.Column('period_end_era_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_end_era_fk'], ['era.id'], ),
    sa.ForeignKeyConstraint(['period_end_month_fk'], ['month.id'], ),
    sa.ForeignKeyConstraint(['period_start_era_fk'], ['era.id'], ),
    sa.ForeignKeyConstraint(['period_start_month_fk'], ['month.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('culture_period_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['culture_period_fk'], ['culture_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('culture')
    op.drop_table('culture_period')
    # ### end Alembic commands ###
