"""empty message

Revision ID: c7c712b120b1
Revises: e7246fe2c2b3
Create Date: 2020-05-15 14:19:42.052169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c712b120b1'
down_revision = 'e7246fe2c2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('essay_person_person_fk_fkey', 'essay_person', type_='foreignkey')
    op.create_foreign_key(None, 'essay_person', 'person', ['person_fk'], ['id'])
    op.add_column('timeline', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline', 'description')
    op.drop_constraint(None, 'essay_person', type_='foreignkey')
    op.create_foreign_key('essay_person_person_fk_fkey', 'essay_person', 'event', ['person_fk'], ['id'])
    # ### end Alembic commands ###
