"""empty message

Revision ID: c8cd56bead4a
Revises: c7c712b120b1
Create Date: 2020-06-01 21:14:35.522431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cd56bead4a'
down_revision = 'c7c712b120b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brainstorm_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('brainstorm_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_fk'], ['brainstorm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brainstorm_thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('chapter', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('brainstorm_fk', sa.Integer(), nullable=True),
    sa.Column('reference_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_fk'], ['brainstorm.id'], ),
    sa.ForeignKeyConstraint(['reference_fk'], ['reference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brainstorm_topic_thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('chapter', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('brainstorm_topic_fk', sa.Integer(), nullable=True),
    sa.Column('reference_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_topic_fk'], ['brainstorm_topic.id'], ),
    sa.ForeignKeyConstraint(['reference_fk'], ['reference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brainstorm_topic_thought')
    op.drop_table('brainstorm_thought')
    op.drop_table('brainstorm_topic')
    op.drop_table('brainstorm')
    # ### end Alembic commands ###
