"""empty message

Revision ID: d47ac9f9883b
Revises: 3959362c23f4
Create Date: 2020-02-06 12:00:08.120455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47ac9f9883b'
down_revision = '3959362c23f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_end_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_end_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
