"""empty message

Revision ID: df2ace9bdfb5
Revises: b89fdcefeaed
Create Date: 2020-06-22 18:57:02.488838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2ace9bdfb5'
down_revision = 'b89fdcefeaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_dataset', sa.Column('background_color', sa.String(), nullable=True))
    op.add_column('chart_dataset', sa.Column('border_color', sa.String(), nullable=True))
    op.add_column('chart_dataset', sa.Column('fill', sa.Boolean(), nullable=True))
    op.add_column('chart_dataset', sa.Column('point_background_color', sa.String(), nullable=True))
    op.add_column('chart_dataset', sa.Column('point_radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_dataset', 'point_radius')
    op.drop_column('chart_dataset', 'point_background_color')
    op.drop_column('chart_dataset', 'fill')
    op.drop_column('chart_dataset', 'border_color')
    op.drop_column('chart_dataset', 'background_color')
    # ### end Alembic commands ###
