"""empty message

Revision ID: f0fb6061be42
Revises: fb31b60e9492
Create Date: 2020-06-24 09:16:14.226168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fb6061be42'
down_revision = 'fb31b60e9492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_legend_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('align', sa.String(), nullable=True),
    sa.Column('full_width', sa.Boolean(), nullable=True),
    sa.Column('reverse', sa.Boolean(), nullable=True),
    sa.Column('chart_options_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_options_fk'], ['chart_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_legend_label_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('box_width', sa.Integer(), nullable=True),
    sa.Column('padding', sa.Integer(), nullable=True),
    sa.Column('use_point_style', sa.Boolean(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('font_style', sa.String(), nullable=True),
    sa.Column('font_color', sa.String(), nullable=True),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('chart_legend_options_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_legend_options_fk'], ['chart_legend_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_legend_label_options')
    op.drop_table('chart_legend_options')
    # ### end Alembic commands ###
