"""empty message

Revision ID: fb31b60e9492
Revises: 169ecf0532c9
Create Date: 2020-06-23 20:03:00.266942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb31b60e9492'
down_revision = '169ecf0532c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_options', sa.Column('maintain_aspect_ratio', sa.Boolean(), nullable=True))
    op.add_column('chart_options', sa.Column('responsive', sa.Boolean(), nullable=True))
    op.drop_constraint('chart_options_chart_title_options_fk_fkey', 'chart_options', type_='foreignkey')
    op.drop_column('chart_options', 'chart_title_options_fk')
    op.add_column('chart_title_options', sa.Column('chart_options_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chart_title_options', 'chart_options', ['chart_options_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chart_title_options', type_='foreignkey')
    op.drop_column('chart_title_options', 'chart_options_fk')
    op.add_column('chart_options', sa.Column('chart_title_options_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chart_options_chart_title_options_fk_fkey', 'chart_options', 'chart_title_options', ['chart_title_options_fk'], ['id'])
    op.drop_column('chart_options', 'responsive')
    op.drop_column('chart_options', 'maintain_aspect_ratio')
    # ### end Alembic commands ###
